version: '3.8'

services:
  # Backend service for development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - DATABASE_PATH=/root/data/school.db
    volumes:
      - ./backend:/app
      - backend_data:/root/data
    working_dir: /app
    command: ["go", "run", "main.go"]
    networks:
      - app-network
    restart: unless-stopped

  # Frontend service for development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge